### ISSUE TITLE
Some movements are done very slow

### ISSUE THREAD

**Issue by casainho** [bitboxelectronics/R2C2_Firmware#6]
I built firmware from last commit (36dc037a) and tested to print the Android magnet(1). As seen on the video(2), it prints however there are some movements that are done very slow, at different velocity they should be done. An example are the Z movement at the end of each layer that happens to be very slow.

I am printing a lot of the Android magnets using latest stable firmware(3) and all the movements are correct. It works very well however this version misses some functionalities like the beep GCode command and others...

(1) http://www.thingiverse.com/thing:10434
(2) http://www.3dprinting-r2c2.com/?q=content/printfbot-prints-new-reprap-3d-printer
(3) https://github.com/bitboxelectronics/R2C2_Firmware/blob/master/stable_bins/R2C2_RepRap_firmware-2011.12.02.bin

**Comment by bobc** [comment]
Kinda weird... I was playing around yesterday with pronterface and found if I hit the X+1 button rapidly the head will slow down then speed up again in a strange way. I think this is the same problem.

I have an idea why it is happening. I think it is because the planner recalculates the movement queue when a new block is added, and that includes the current movement. In the previous acceleration algorithm that works ok, the stepper module is able to handle changes "on the fly" to the current movement. The new acceleration algorithm is only calculated at the start of a block, so if the planner changes the parameters on the current movement these are not picked up.

So what happens is that the first block decelerates as it was originally programmed. The second block continues at the previous speed, which is now slower than the planner specified, until it reaches the decel point where it will suddenly speed up again to what the planner specified. This seems to match the symptoms described.

I haven't noticed the problem while printing, but it will be sensitive to timing issues.

I also suspect this is the underlying cause of the Z homing issue. I added a sync_queue() for that problem, which prevents the planner recalculating the current block.

**Comment by casainho** [comment]
Bob, could you please remind me why the changes on the (4bef47fca0) "Implement accurate acceleration profiles"? Wasn't the code based on Grbl?? What was your motivation, what is better, on the new changes?

"So what happens is that the first block decelerates as it was originally programmed. The second block continues at the previous speed, which is now slower than the planner specified, until it reaches the decel point where it will suddenly speed up again to what the planner specified. This seems to match the symptoms described." ---> yes.

"I also suspect this is the underlying cause of the Z homing issue. I added a sync_queue() for that problem, which prevents the planner recalculating the current block." ---> yes, seems to be that.

**Comment by bobc** [comment]
Please refer to https://groups.google.com/forum/?fromgroups#!topic/r2c2-reprap-and-cnc/Mp8_gMqjqac

**Comment by bobc** [comment]
OK, I can now confirm this was a bug/feature in the grbl code I ported from chamnit. Each block added to the move queue 
causes the head to be recalculated, even if it is currently in use. With chamnit's code, this is not too big a problem because the code calculates the acceleration based on the accel_until/decel_after points, If these change on the fly then most of the time it adapts ok. In my case, I am effectively precomputing the acceleration based on the trapezoid profile, so attempting to change the profile on the fly gets messed up.

Hopefully it should be easy to lock the head of the queue to prevent the planner from recalculating it. The impact of this is that the first move in the queue will always decel to zero at the end of the move. 2nd and subsequent entries will be calculated according to the cornering speed. This will affect the first move the printer does, after that as long as there are at least 2 entries in the move queue then it will not be affected.

**Comment by talib-zz** [comment]
Dear casainho

I want to contact you because I have some problems and need you ur e-mail you may please let me know if it is possible. you can contact me at rajatalib@gmail.com.

Best Regards

**Comment by casainho** [comment]
2012/4/12 talib
reply@reply.github.com:

> Dear casainho
> 
> I want to contact you because I have some problems and need you ur e-mail you may please let me know if it is possible. you can contact me at rajatalib@gmail.com.

Hello.

You can contact-me using this e-mail.

> Best Regards
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bitboxelectronics/R2C2_Firmware/issues/6#issuecomment-5086998

## 

Cumprimentos,
Jorge Pinto
E-mail: casainho@gmail.com
Telemóvel: 927145983

Incubadora da Universidade de Aveiro
Edifício I, Sala 82
Campus Universitário de Santiago
3810-193 Aveiro
+351 234 380 314
www.bitbox.pt

**Comment by bobc** [comment]
This problem seems to have improved, if not completely fixed. It is difficult to reproduce, so we need more test cases that can reproduce the problem.
